test-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

test-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

test-app/app/models/category.rb
class Category < ApplicationRecord
end

test-app/app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
end

test-app/app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

test-app/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

test-app/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates_presence_of :description, :category, :price

  def full_description
    "#{self.description} - #{self.price}"
  end
  
end

test-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

test-app/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email)
    end
end

test-app/app/helpers/application_helper.rb
module ApplicationHelper
end

test-app/app/helpers/customers_helper.rb
module CustomersHelper
end

test-app/app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Name:</strong>
    <%= customer.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

</div>

test-app/app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

test-app/app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

test-app/app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer %>
    </p>
  <% end %>
</div>

<%= link_to "New customer", new_customer_path %>
<br/>
<a href="#" id="my-link">Add Message</a>
<div id="my-div"></div>
<script>
 var $link = document.querySelector("#my-link");
 $link.addEventListener('click', function(e){
 e.preventDefault();
 setTimeout(function(){
 document.querySelector("#my-div").innerHTML =
"<h1>Yes!<h1>";
 }, 4000);
 }, false)
</script>

test-app/app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

test-app/app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>

test-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>